# Native Simulator Core Settings
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=4096

# Native Simulator SDL Display & Graphic Drivers
CONFIG_DISPLAY=y
CONFIG_SDL_DISPLAY=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_LOG=y
